### PR TITLE
node v8.9.3

### PR DESCRIPTION
**Pull request by roytan883**

### CODE REVIEW

**Comment by roytan883** [comment]
node v8.9.3

**Comment by neoz** [comment]
@roytan883 i got the error when compile node using your repo
c:\users\xxUserxx\appdata\local\temp\nodec\node-8.9.1-1.6.0\deps\libsquash\include\squash/common.h(76): error C3646: 'block': unknown override specifier (com piling source file src\node_main.cc) [C:\Users\xxUserxx\AppData\Local\Temp\nodec\node-8.9.1-1.6.0\node.vcxproj]
c:\users\xxUserxx\appdata\local\temp\nodec\node-8.9.1-1.6.0\deps\libsquash\include\squash/common.h(76): error C4430: missing type specifier - int assumed. No te: C++ does not support default-int (compiling source file src\node_main.cc) [C:\Users\xxUserxx\AppData\Local\Temp\nodec\node-8.9.1-1.6.0\node.vcxproj]
c:\users\xxUserxx\appdata\local\temp\nodec\node-8.9.1-1.6.0\deps\libsquash\include\squash/dir.h(34): error C3646: 'offset': unknown override specifier (compi ling source file src\node_main.cc) [C:\Users\xxUserxx\AppData\Local\Temp\nodec\node-8.9.1-1.6.0\node.vcxproj]
c:\users\xxUserxx\appdata\local\temp\nodec\node-8.9.1-1.6.0\deps\libsquash\include\squash/dir.h(34): error C2059: syntax error: ',' (compiling source file sr c\node_main.cc) [C:\Users\xxUserxx\AppData\Local\Temp\nodec\node-8.9.1-1.6.0\node.vcxproj]
c:\users\xxUserxx\appdata\local\temp\nodec\node-8.9.1-1.6.0\deps\libsquash\include\squash/dir.h(34): error C2238: unexpected token(s) preceding ';' (compilin g source file src\node_main.cc) [C:\Users\xxUserxx\AppData\Local\Temp\nodec\node-8.9.1-1.6.0\node.vcxproj]
c:\users\xxUserxx\appdata\local\temp\nodec\node-8.9.1-1.6.0\deps\libsquash\include\squash/dir.h(44): error C3646: 'offset': unknown override specifier (compi ling source file src\node_main.cc) [C:\Users\xxUserxx\AppData\Local\Temp\nodec\node-8.9.1-1.6.0\node.vcxproj]
c:\users\xxUserxx\appdata\local\temp\nodec\node-8.9.1-1.6.0\deps\libsquash\include\squash/dir.h(44): error C2059: syntax error: ',' (compiling source file sr c\node_main.cc) [C:\Users\xxUserxx\AppData\Local\Temp\nodec\node-8.9.1-1.6.0\node.vcxproj]
c:\users\xxUserxx\appdata\local\temp\nodec\node-8.9.1-1.6.0\deps\libsquash\include\squash/dir.h(44): error C2238: unexpected token(s) preceding ';' (compilin g source file src\node_main.cc) [C:\Users\xxUserxx\AppData\Local\Temp\nodec\node-8.9.1-1.6.0\node.vcxproj]
c:\users\xxUserxx\appdata\local\temp\nodec\node-8.9.1-1.6.0\deps\libsquash\include\squash/dir.h(81): error C4430: missing type specifier - int assumed. Note:  C++ does not support default-int (compiling source file src\node_main.cc) [C:\Users\xxUserxx\AppData\Local\Temp\nodec\node-8.9.1-1.6.0\node.vcxproj]
c:\users\xxUserxx\appdata\local\temp\nodec\node-8.9.1-1.6.0\deps\libsquash\include\squash/dir.h(81): error C2086: 'int sqfs_off_t': redefinition (compiling s ource file src\node_main.cc) [C:\Users\xxUserxx\AppData\Local\Temp\nodec\node-8.9.1-1.6.0\node.vcxproj]

Is there any hint ?

**Comment by roytan883** [comment]
@neoz never tested on windows, hope you can change to linux

**Comment by zhoutk** [comment]
@roytan883 your work is perfect！I use on macbook success, thanks!

**Comment by pmq20** [comment]
I'm closing it in the sight of newer versions of Node.js being release, I'll upgrade to the latest version ASAP. Thank you for the PR!

**Pull request closed without merging**
